version: '3'
   
services:
  # app:
  #   container_name: app
  #   restart: always
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   links:
  #     - db
  #   environment:
  #     - PORT=5000
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_USERNAME=your_db_username
  #     - DB_PASSWORD=your_db_password
  #     - DB_DATABASE=your_database
  #     - JWT_SECRET=your_jwt_secret
  #   depends_on:
  #     - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
